# - range(0, len(n)) generates a sequence of numbers starting from 0 up to len(n) - 1. len(n) is the length of the list n.
# - for i in iterates over each number in the sequence generated by range(0, len(n)).

# So, if n is a list with 5 elements, range(0, len(n)) will generate a sequence of numbers from 0 to 4. The for loop will then iterate over these numbers. In each iteration, i will be the next number in the sequence.
def booooo(n):
    for i in range(0, len(n)):
        print('booooo')


# booooo([1, 2, 3, 4, 5])  # O(1)


# This function creates an array of 'hi' strings. The length of the array is determined by the input parameter 'n'.
def arrayOfHiNTimes(n):
    # Initialize an empty list
    hiArray = []
    
    # Loop 'n' times
    for i in range(n):
        # Append the string 'hi' to the list on each iteration
        hiArray.append('hi')
    
    # Return the final list
    return hiArray

# Call the function with 'n' as 6 and print the result
# The time complexity of this function is O(n) because it performs 'n' operations where 'n' is the size of the input.
print(arrayOfHiNTimes(6))  # O(n)
